### ISSUE TITLE
Number of frames in the Choke1 video sequence

### ISSUE THREAD

**Issue by Cassio-4** [hertasecurity/LTFT#1]
Hello, I read your paper and am planning to use this Dataset on my thesis. I am writing a python script to separate the desired frames into folders following the instructions given. 

However, when preparing the Choke1 video I noticed that the sequences P2E_S5_C2.1, P2E_S5_C1.1 and P2E_S5_C3.1 have only 806 frames each, totalling **2418** frames instead of the **2526** frames you annotated.
Would you kindly point me in the right direction? Am I missing frames?

Thank you, respectfully.

**Comment by vitoralbiero** [comment]
Hello @Cassio-4,

I was also facing this issue. Their annotations have an additional 36 background frames for each video on the Choke1 sequence. If you remove those annotations (remove the first 36 annotations with 0s for each sequence on choke1.txt), the Choke1 video and annotations will be in sync.
For Choke2, their annotations have 42 background frames less than the videos on ChokePoint, so you would need to remove the first 42 frames for each video on Choke2.
Also, the correct sequence for Choke2 is P2L_S5_C2.1, P2L_S5_C3.1, and P2L_S5_C1.1, instead of what is on the readme.

Hope this helps you!

**Comment by Cassio-4** [comment]
Thank you very much @vitoralbiero!

After a whole week trying to build this dataset, I eventually figured these details out. What I also managed to gather is that the Shibuya sequence was annotated on the video's original 29,97 FPS, instead of 25 FPS. And that the Terminal2, 3 and 4 video's annotations start at about 11 frames after the provided timestamps. 
Overall this is an interesting novel dataset, but it was a little frustrating trying to sync and figure out all these undocumented details.

Allow me to thank you once again, and best of luck!
